card:
  endpoint: https://shielded-sierra-07398.herokuapp.com

insurance:
  endpoint: https://nameless-meadow-41021.herokuapp.com

ePay:
  terminalID: 67e34d63-102f-4bd1-898e-370781d0074d
  clientID: test
  clientSecret: yF587AV9Ms94qN2QShFzVR3vFnWkhjbAK3sG
  oauthEndpoint: https://testoauth.homebank.kz/epay2
  endpoint: https://testepay.homebank.kz/api
  jsLink: https://test-epay.homebank.kz/payform/payment-api.js
  backLink: https://hkazynav2.herokuapp.com
  postLink: https://hidden-tundra-74400.herokuapp.com/api/v1/payments/callback
  amount: 25